workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    
    environment:
      java: 17
    
    triggering:
      events:
        - push
        - pull_request
    
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    
    scripts:
      - name: Set up gradle permissions
        script: chmod +x gradlew
      
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug \
            -x lint \
            --no-daemon
    
    artifacts:
      - build/outputs/apk/debug/**/*.apk
    
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
