workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      java: 17
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Build APK
        script: |
          chmod +x gradlew
          ./gradlew build assembleDebug -x lint
    artifacts:
      - build/outputs/apk/debug/**/*.apk
