workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      java: 17
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build APK
        script: |
          chmod +x ./gradlew
          ./gradlew build --no-daemon
      - name: Build Release APK
        script: |
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - build/outputs/apk/debug/app-debug.apk
      - build/outputs/apk/release/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
