workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      java: 17
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install gradle
        script: |
          brew install gradle
      - name: Build APK
        script: |
          gradle build -x lint
      - name: Build Release APK
        script: |
          gradle assembleRelease -x lint
    artifacts:
      - build/outputs/apk/debug/app-debug.apk
      - build/outputs/apk/release/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
